### ISSUE TITLE
7.3.2的代码运行有问题

### ISSUE THREAD

**Issue by EdmundTheRadiance** [Ovilia/ThreeExample.js#10]
![image](https://cloud.githubusercontent.com/assets/9878880/18777892/2ab69d96-81a4-11e6-9a59-32475ebe71b3.png)

http://zhangwenli.com/ThreeExample.js/Chapter7/7.3.2.html

**Comment by Ovilia** [comment]
@EdmundTheRadiance 因为 Three.js 的库被我更新了，但是 demo 现在只改了一部分……暂缓……

**Comment by Ovilia** [comment]
cff735cc25b91eab68c1be0c8472e5fadbedafb7 已解决
