### ISSUE TITLE
十分不好意思，能问你一个svg的小问题吗

### ISSUE THREAD

**Issue by screetBloom** [Ovilia/ThreeExample.js#15]
实在是找不到可以问的人，也没有搜到切实可用的demo，一直都会关注你的相关博客也包括IFE的相关消息，感觉你比较懂图形图像类的问题，所以冒昧的问一下

![问题详情](http://7xl4c6.com1.z0.glb.clouddn.com/FjrJLCvZvezuVEywRitfvpM3g2SG)

1.  用svg做一个环形的进度条一样的东西，这个很好做（用的 stroke-dasharray）
2.  但是，我需要再做一个小圆，随着环形慢慢变成一个圆时一直和头部在一起移动（这个不懂）

这个能稍微指点一下我吗

**Comment by Ovilia** [comment]
做增加一个圆就行了

**Comment by screetBloom** [comment]
好的，谢谢您的回复， :smiley:    我最终实现了这个效果
如果您感兴趣的话，可以看看我写的这个[demo](http://115.159.100.155/svg/progress/final.html)
即[http://115.159.100.155/svg/progress/final.html](http://115.159.100.155/svg/progress/final.html)

**Comment by Ovilia** [comment]
赞！👍

**Comment by screetBloom** [comment]
@Ovilia   你好，今天我看了你往期的一篇blog，感到很惭愧；
很感谢从你这里明白了一些“江湖招式”，谢谢    :thumbsup:  
![博客阅读截图](http://7xl4c6.com1.z0.glb.clouddn.com/Fr8a81MEpszbGnR_tAKVHJtuKo4E)
