### ISSUE TITLE
跟着教程写的demo仓库

### ISSUE THREAD

**Issue by SilentFlute** [Ovilia/ThreeExample.js#19]
这是一个我自己跟着羡辙的threejs教程学习时写的一个demo仓库, 于近期建立, 因为羡辙的demo历史久远, 有些api已经被废弃, 加上学习代码光看不行, 必须要自己动手敲, 于是就有了这个仓库, 想着自己看不如放issue中和大家一起交流交流, 不敢说写的多好, 只希望能起到一个抛砖引玉的作用, 大家多多交流, 共同进步, 多少有些不足之处, 还望大家谅解

仓库地址是: [three-learn](https://gitee.com/silent_flute/three-learn), 这是一个码云的仓库, 然后我的码云主页里也有我的邮箱, 欢迎交流探讨, github的gmail用得比较少

另外就是这个仓库是用的[umi3.x](https://umijs.org/zh-CN)搭建的, 还使用了[react](https://reactjs.org/), 关于`umi3.x`不需要额外的知识, 了解它将我们`/pages`下面的目录封装成了一个个路由即可, `react`也只是简单的使用, 只需了解以下两点即可:
1. 只有在`componentDidMount`中才能访问`dom`节点, 因此创建渲染器的代码只能写在`componentDidMount`中
2. 其他代码可不必要写在`componentDidMount`中, 当然了, 简单的渲染则可以将所有代码都写在`componentDidMount`中

**Comment by Ovilia** [comment]
赞啊，教程我是很多年写的了，一方面 API 过时，一方面个人能力也有限。如果你发现问题顺手能提个 PR 的话就最好啦~

**Comment by SilentFlute** [comment]
啊, 我居然没想到给你提pr怎么...[捂脸]
